name: 'Terraform'

on: [workflow_dispatch]

jobs:    
     terraform-credentials-cloud:
       name: 'Terraform Cloud Credentials'
       runs-on: ${{ matrix.os }}
       strategy:
           matrix:
            os: [ubuntu-latest]
       env:
         TF_TOKEN: 'pI01CGKJrT5nIw.atlasv1.tFDFUypt0B8UAXdBu4NWkxx9nFR5lIIkFZ5vZ6HCAIxjD66plNNB7M9GemXPMJlFjDQ'
       steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: ./
          with:
            cli_config_credentials_token: ${{ env.TF_TOKEN }}

      


  

    
