name: 'Setup Terraform'

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  

jobs:    
     terraform-credentials-cloud:
       name: 'Terraform Cloud Credentials'
       env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: true
         TF_TOKEN: 'pI01CGKJrT5nIw.atlasv1.tFDFUypt0B8UAXdBu4NWkxx9nFR5lIIkFZ5vZ6HCAIxjD66plNNB7M9GemXPMJlFjDQ'
         
       runs-on: ${{ matrix.os }}
       strategy:
           matrix:
            os: [ubuntu-latest]

       # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
       defaults:
         run:
          shell: bash
       
       steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: refrence action 
          uses: ShivaKarki/action-terraform@v0.5
          with:
             TF_TOKEN: ${{env.TF_TOKEN }}
      

      


  

    
