name: 'Terraform'

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform login'
    runs-on: ubuntu-latest
    
    steps:
      - name: reference terraform action
        uses: ShivaKarki/terraform_action@v1.8
        with:
            TF_TOKEN: ${{ secrets.TF_TOKEN }}
        
      


  

    
