name: 'Terraform'

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform login'
    runs-on: ubuntu-latest
    
    steps:
      - name: reference terraform action
        uses: ShivaKarki/terraform_action@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN}}
      


  

    
